<?xml version="1.0" encoding="utf-8"?><Database Name="WeixinRoboot" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost,9125;Initial Catalog=WeixinRoboot;Persist Security Info=True;User ID=sa" SettingsObjectName="WeixinRoboot.Properties.Settings" SettingsPropertyName="WeixinRobootConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Game_Result" Member="Game_Result">
    <Type Name="Game_Result">
      <Column Name="GameName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameResult" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GameTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BigSmall" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SingleDouble" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DragonTiger" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="GamePrivatePeriod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="InsertDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaoHua_GameResult" Member="TaoHua_GameResult">
    <Type Name="TaoHua_GameResult">
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameResult" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Game_ChongqingshishicaiPeriodMinute" Member="Game_ChongqingshishicaiPeriodMinute">
    <Type Name="Game_ChongqingshishicaiPeriodMinute">
      <Column Name="GameType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PeriodIndex" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TimeMinute" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Private_Period" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Private_day" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PIC_EndSendLog" Member="PIC_EndSendLog">
    <Type Name="PIC_EndSendLog">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SendDate" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_BossID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WX_PicErrorLog" Member="WX_PicErrorLog">
    <Type Name="WX_PicErrorLog">
      <Column Name="aspnet_Userid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SendId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UploadTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UploadResult" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SendTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SendResult" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_BounsConfig" Member="WX_BounsConfig">
    <Type Name="WX_BounsConfig">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RowNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartBuyPeriod" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="EndBuyPeriod" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="StartBuyAverage" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="EndBuyAverage" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="FixNumber" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="FlowPercent" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="IfDivousPercent" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_ResultFootBall_Last" Member="Game_ResultFootBall_Last">
    <Type Name="Game_ResultFootBall_Last">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameKey" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="A_Team" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="B_Team" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="HalfPoint" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LastPoint" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="EndState" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MatchBallType" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MatchClassName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LiveBallLastSendTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_Football_LastRatio" Member="Game_Football_LastRatio">
    <Type Name="Game_Football_LastRatio">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameKey" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameVS" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="A_WIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Winless" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="B_Win" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BIGWIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Total" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SMALLWIN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_A_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_A_SAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_A_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_SAME_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_SAME_SAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_SAME_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_B_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_B_SAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R_B_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R1_0_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R1_0_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R2_0_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R2_0_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R2_1_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R2_1_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R3_0_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R3_0_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R3_1_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R3_1_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R3_2_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R3_2_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_0_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_0_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_1_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_1_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_2_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_2_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_3_A" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_3_B" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R0_0" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R1_1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R2_2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R3_3" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="R4_4" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ROTHER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="A_Team" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="B_Team" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GameTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserGameLog_Football" Member="WX_UserGameLog_Football">
    <Type Name="WX_UserGameLog_Football">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="transtime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameKey" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameVS" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="BuyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BuyRatio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BuyMoney" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="HaveOpen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ResultMoney" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="A_WIN" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Winless" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="B_WIN" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="BIGWIN" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Total" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SMALLWIN" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_A_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_A_SAME" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_A_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_SAME_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_SAME_SAME" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_SAME_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_B_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_B_SAME" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R_B_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R1_0_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R1_0_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R2_0_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R2_0_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R2_1_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R2_1_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R3_0_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R3_0_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R3_1_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R3_1_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R3_2_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R3_2_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_0_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_0_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_1_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_1_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_2_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_2_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_3_A" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_3_B" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R0_0" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R1_1" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R2_2" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R3_3" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="R4_4" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ROTHER" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="A_Team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="B_Team" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GameTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MatchClass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_ResultFootBall" Member="Game_ResultFootBall">
    <Type Name="Game_ResultFootBall">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameID" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="A_FrontHalf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="A_EndHalf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="B_FrontHalf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="B_EndHalf" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GameVS" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_FootBall_VSRatios" Member="Game_FootBall_VSRatios">
    <Type Name="Game_FootBall_VSRatios">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameKey" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RatioIndex" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="A_WIN" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Winless" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="B_WIN" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="BIGWIN" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="Total" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="SMALLWIN" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="RatioType" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R1_0_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R1_0_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R2_0_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R2_0_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R2_1_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R2_1_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R3_0_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R3_0_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R3_1_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R3_1_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R3_2_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R3_2_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_0_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_0_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_1_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_1_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_2_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_2_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_3_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_3_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R0_0" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R1_1" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R2_2" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R3_3" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R4_4" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="ROTHER" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_A_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_A_SAME" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_A_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_SAME_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_SAME_SAME" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_SAME_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_B_A" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_B_SAME" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="R_B_B" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="RCompanyType" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_ResultFootBallPointLog_Last" Member="Game_ResultFootBallPointLog_Last">
    <Type Name="Game_ResultFootBallPointLog_Last">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameKey" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PointIndex" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PointTime" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PointTeam" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_FootBall_VS" Member="Game_FootBall_VS">
    <Type Name="Game_FootBall_VS">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameKey" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LastAliveTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="A_Team" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="B_Team" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GameType" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="HeadDiv" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RowData" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RowDataWithName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GameVS" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="GameTime" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MatchClass" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Jobid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserReplyLog" Member="WX_UserReplyLog">
    <Type Name="WX_UserReplyLog">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceiveTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceiveContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReplyContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReplyTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HaveDeal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SourceType" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_msgType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveIndex" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserGameLog_Bonus" Member="WX_UserGameLog_Bonus">
    <Type Name="WX_UserGameLog_Bonus">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameName" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Buy_Value" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BonusBuyValueCondition" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="BasicRatio" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserChangeLog" Member="WX_UserChangeLog">
    <Type Name="WX_UserChangeLog">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChangeTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RemarkType" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChangePoint" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="NeedNotice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HaveNotice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FinalStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BuyValue" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameLocalPeriod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangeLocalDay" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChangeIndex" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameMode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_TimeHKSix" Member="Game_TimeHKSix">
    <Type Name="Game_TimeHKSix">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OpenTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_ResultHKSix" Member="Game_ResultHKSix">
    <Type Name="Game_ResultHKSix">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Num1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num5" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Num6" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumSpec" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GameTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AnmialSpec" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Anmial1" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Anmial2" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Anmial3" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Anmial4" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Anmial5" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="Anmial6" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserGameLog_HKSix" Member="WX_UserGameLog_HKSix">
    <Type Name="WX_UserGameLog_HKSix">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(250) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HaveOpen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ResultMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BuyValue" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyRatio" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_WuFenPeriodMinute" Member="Game_WuFenPeriodMinute">
    <Type Name="Game_WuFenPeriodMinute">
      <Column Name="GameType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PeriodIndex" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TimeMinute" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Private_Peirod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Private_Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserGameLog" Member="WX_UserGameLog">
    <Type Name="WX_UserGameLog">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameName" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameResult" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gr_NumTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gr_BigSmall" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Gr_SingleDouble" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Gr_DragonTiger" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Buy_Type" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Buy_Value" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Buy_Ratio" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Buy_Point" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Result_Point" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Result_HaveProcess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GameLocalPeriod" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GP_LastModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Buy_Ratio_Full1" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Buy_Ratio_Full2" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Buy_Ratio_Full3" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Buy_Ratio_Full4" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Buy_Ratio_Full5" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MemberGroupName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="OpenMode" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_WebSendPICSettingMatchClass" Member="WX_WebSendPICSettingMatchClass">
    <Type Name="WX_WebSendPICSettingMatchClass">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatchBallType" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatchClassName" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SendAny" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_BasicRatio" Member="Game_BasicRatio">
    <Type Name="Game_BasicRatio">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyValue" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MinBuy" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="MaxBuy" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="BasicRatio" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="OrderIndex" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IncludeMin" Type="System.Boolean" DbType="Bit NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BonusBuyValueCondition" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_PCTransMoneyLog" Member="WX_PCTransMoneyLog">
    <Type Name="WX_PCTransMoneyLog">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BillTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FromUserName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="TransMoney" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HaveProces" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_PCSendPicSettingRandomTalk" Member="WX_PCSendPicSettingRandomTalk">
    <Type Name="WX_PCSendPicSettingRandomTalk">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MessageIndex" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MessageContent" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RandomMinute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreSendTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="WX_PCSendPicSetting_WX_PCSendPicSettingRandomTalk" Member="WX_PCSendPicSetting" ThisKey="aspnet_UserID,WX_UserName,WX_SourceType" OtherKey="aspnet_UserID,WX_UserName,WX_SourceType" Type="WX_PCSendPicSetting" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UserVirtualFile" Member="aspnet_UserVirtualFile">
    <Type Name="aspnet_UserVirtualFile">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FileID" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FileContenxt" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.WX_WebSendPICSetting" Member="WX_WebSendPICSetting">
    <Type Name="WX_WebSendPICSetting">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="footballPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="bassketballpic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="balluclink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ballinterval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="card" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="cardname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="shishicailink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NumberPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="dragonpic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="numericlink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="dragonlink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastBallSendTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumberAndDragonPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ballend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ballstart" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="balllivepoint" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HKSixResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NumberDragonTxt" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NiuNiuPic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoBigSmallSingleDoublePIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSendPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PIC_StartHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIC_StartMinute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PIC_EndHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pic_EndMinute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PreSendGameType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserReply" Member="WX_UserReply">
    <Type Name="WX_UserReply">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsReply" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="RemarkName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IsReceiveTransfer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCaculateFuli" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WeChatID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsBoss" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsBallPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FiveMinuteMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HkMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AozcMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChongqingMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengXunShiFenMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XinJiangMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengXunWuFenMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VRMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengXunShiFenXinMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengXunWuFenXinMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HeNeiWuFenMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_PCSendPicSetting" Member="WX_PCSendPicSetting">
    <Type Name="WX_PCSendPicSetting">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OpenResult" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NumberDragonTxt" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Is_Reply" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OpenPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OpenHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OpenMinue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BounsTimeStopPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EndPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EndHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndMinute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DuringFiveMinute" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OpenPlease" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DragonTigerOne" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WechatCard" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastPeriod" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Text1" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Text1Minute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Text2" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Text2Minute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Text3" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="Text3Minute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DragonPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FootballPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BasketballPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BallLink" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BallInterval" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WX_UserTMPID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Can_Use" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TMP_Basketball" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TMP_Football" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TMP_Text1Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TMP_Text2Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TMP_Text3Time" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GroupOwner" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PreSendPeriod" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="NextSendString" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="NumberText" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FiveMinuteMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HkMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AozcMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChongqingMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RefreshBill" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tengxunshifen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BeijingsaichePK10" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Tengxunwufen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="VRChongqing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XinJiangMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Text1PicPath" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="NiuNiuPic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NoBigSmallSingleDoublePIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NiuNiuBigSmallPic" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengxunshifenXin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengxunwufenXin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HeNeiWuFenMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="WX_PCSendPicSetting_WX_PCSendPicSettingRandomTalk" Member="WX_PCSendPicSettingRandomTalk" ThisKey="aspnet_UserID,WX_UserName,WX_SourceType" OtherKey="aspnet_UserID,WX_UserName,WX_SourceType" Type="WX_PCSendPicSettingRandomTalk" />
    </Type>
  </Table>
</Database>