<?xml version="1.0" encoding="utf-8"?><Database Name="Weixinroboot" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=superserver,9125;Initial Catalog=Weixinroboot;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WeixinrobootConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WX_UserReply" Member="WX_UserReply">
    <Type Name="WX_UserReply">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsReply" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="RemarkName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="IsReceiveTransfer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsCaculateFuli" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="WeChatID" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsBoss" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsBallPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FiveMinuteMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HkMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AozcMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ChongqingMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengXunShiFenMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XinJiangMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengXunWuFenMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserReplyLog" Member="WX_UserReplyLog">
    <Type Name="WX_UserReplyLog">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(350) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceiveTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceiveContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReplyContent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ReplyTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HaveDeal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SourceType" Type="System.String" DbType="NVarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_msgType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ReceiveIndex" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersNewGameResultSend" Member="aspnet_UsersNewGameResultSend">
    <Type Name="aspnet_UsersNewGameResultSend">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsNewSend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActiveCode" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="IsBlock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSendPIC" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsReceiveOrder" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaxPlayerCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bossaspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="SendImageEnd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendImageStart" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendImageEnd2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendImageEnd3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendImageEnd4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendImageStart2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendImageStart3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SendImageStart4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageEndText" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ImageTopText" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="BlockEndHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BlockEndMinute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BlockStartHour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BlockStartMinute" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LeiDianPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NoxPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LeiDianSharePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NoxSharePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AdbLeidianMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="AdbNoxMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TwoTreeNotSingle" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="XinJiangMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TengXunShiFenMode" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FuliRatio" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
      <Column Name="LiuShuiRatio" Type="System.Decimal" DbType="Decimal(18,5)" CanBeNull="true" />
      <Column Name="Thread_AoZhouCai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_ChongQingShiShiCai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_TengXunShiFen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_TengXunWuFen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_VRChongqing" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_WuFen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_XinJiangShiShiCai" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_TengXunShiFenXin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_TengXunWuFenXin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Thread_HeNeiWuFen" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_Users">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Users_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Membership">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Users_aspnet_Membership" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_BasicRatio" Member="Game_BasicRatio">
    <Type Name="Game_BasicRatio">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyValue" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MinBuy" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="MaxBuy" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" CanBeNull="false" />
      <Column Name="BasicRatio" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="OrderIndex" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IncludeMin" Type="System.Boolean" DbType="Bit NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BonusBuyValueCondition" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="WX_SourceType" Type="System.String" DbType="NVarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Enable" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_BounsConfig" Member="WX_BounsConfig">
    <Type Name="WX_BounsConfig">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RowNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StartBuyPeriod" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="EndBuyPeriod" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="StartBuyAverage" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="EndBuyAverage" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="FixNumber" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="FlowPercent" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="IfDivousPercent" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
    </Type>
  </Table>
</Database>