<?xml version="1.0" encoding="utf-8"?><Database Name="WeinxinRoboot" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=WeinxinRoboot;Persist Security Info=True;User ID=sa" SettingsObjectName="WeixinRoboot.Properties.Settings" SettingsPropertyName="WeinxinRobootConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.aspnet_Users" Member="aspnet_Users">
    <Type Name="aspnet_Users">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="LoweredUserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="MobileAlias" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="IsAnonymous" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="aspnet_Users_aspnet_Membership" Member="aspnet_Membership" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Membership" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_Membership" Member="aspnet_Membership">
    <Type Name="aspnet_Membership">
      <Column Name="ApplicationId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordFormat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MobilePIN" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="LoweredEmail" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordQuestion" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="PasswordAnswer" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsLockedOut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLoginDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastPasswordChangedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastLockoutDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FailedPasswordAnswerAttemptWindowStart" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Comment" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="aspnet_Users_aspnet_Membership" Member="aspnet_Users" ThisKey="UserId" OtherKey="UserId" Type="aspnet_Users" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserReply" Member="WX_UserReply">
    <Type Name="WX_UserReply">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsReply" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="RemarkName" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserChangeLog" Member="WX_UserChangeLog">
    <Type Name="WX_UserChangeLog">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ChangeTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="RemarkType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ChangePoint" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="NeedNotice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="HaveNotice" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_ChongqingshishicaiPeriodMinute" Member="Game_ChongqingshishicaiPeriodMinute">
    <Type Name="Game_ChongqingshishicaiPeriodMinute">
      <Column Name="GameType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PeriodIndex" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TimeMinute" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Private_Period" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Private_day" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserGameLog" Member="WX_UserGameLog">
    <Type Name="WX_UserGameLog">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameResult" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gr_NumTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Gr_BigSmall" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Gr_SingleDouble" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Gr_DragonTiger" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Buy_Type" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Buy_Value" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Buy_Ratio" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Buy_Point" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Result_Point" Type="System.Decimal" DbType="Decimal(18,6)" CanBeNull="true" />
      <Column Name="Result_HaveProcess" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="GameLocalPeriod" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GP_LastModify" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_BasicRatio" Member="Game_BasicRatio">
    <Type Name="Game_BasicRatio">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyType" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BuyValue" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MinBuy" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaxBuy" Type="System.Decimal" DbType="Decimal(18,3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BasicRatio" Type="System.Decimal" DbType="Decimal(18,3)" CanBeNull="true" />
      <Column Name="OrderIndex" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IncludeMin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WX_UserReplyLog" Member="WX_UserReplyLog">
    <Type Name="WX_UserReplyLog">
      <Column Name="WX_UserName" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceiveTime" Type="System.DateTime" DbType="DateTime NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReceiveContent" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ReplyContent" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="ReplyTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HaveDeal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SourceType" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Game_Result" Member="Game_Result">
    <Type Name="Game_Result">
      <Column Name="GameName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GamePeriod" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GameResult" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GameTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NumTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BigSmall" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="SingleDouble" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="DragonTiger" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="GamePrivatePeriod" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.aspnet_UsersNewGameResultSend" Member="aspnet_UsersNewGameResultSend">
    <Type Name="aspnet_UsersNewGameResultSend">
      <Column Name="aspnet_UserID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IsNewSend" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ActiveCode" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
    </Type>
  </Table>
</Database>