#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeixinRoboot.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WeinxinRoboot")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertaspnet_Users(aspnet_Users instance);
    partial void Updateaspnet_Users(aspnet_Users instance);
    partial void Deleteaspnet_Users(aspnet_Users instance);
    partial void Insertaspnet_Membership(aspnet_Membership instance);
    partial void Updateaspnet_Membership(aspnet_Membership instance);
    partial void Deleteaspnet_Membership(aspnet_Membership instance);
    partial void InsertWX_UserReply(WX_UserReply instance);
    partial void UpdateWX_UserReply(WX_UserReply instance);
    partial void DeleteWX_UserReply(WX_UserReply instance);
    partial void InsertGame_ChongqingshishicaiPeriodMinute(Game_ChongqingshishicaiPeriodMinute instance);
    partial void UpdateGame_ChongqingshishicaiPeriodMinute(Game_ChongqingshishicaiPeriodMinute instance);
    partial void DeleteGame_ChongqingshishicaiPeriodMinute(Game_ChongqingshishicaiPeriodMinute instance);
    partial void InsertGame_BasicRatio(Game_BasicRatio instance);
    partial void UpdateGame_BasicRatio(Game_BasicRatio instance);
    partial void DeleteGame_BasicRatio(Game_BasicRatio instance);
    partial void InsertWX_UserReplyLog(WX_UserReplyLog instance);
    partial void UpdateWX_UserReplyLog(WX_UserReplyLog instance);
    partial void DeleteWX_UserReplyLog(WX_UserReplyLog instance);
    partial void InsertGame_Result(Game_Result instance);
    partial void UpdateGame_Result(Game_Result instance);
    partial void DeleteGame_Result(Game_Result instance);
    partial void Insertaspnet_UsersNewGameResultSend(aspnet_UsersNewGameResultSend instance);
    partial void Updateaspnet_UsersNewGameResultSend(aspnet_UsersNewGameResultSend instance);
    partial void Deleteaspnet_UsersNewGameResultSend(aspnet_UsersNewGameResultSend instance);
    partial void InsertWX_UserGameLog(WX_UserGameLog instance);
    partial void UpdateWX_UserGameLog(WX_UserGameLog instance);
    partial void DeleteWX_UserGameLog(WX_UserGameLog instance);
    partial void InsertWX_UserChangeLog(WX_UserChangeLog instance);
    partial void UpdateWX_UserChangeLog(WX_UserChangeLog instance);
    partial void DeleteWX_UserChangeLog(WX_UserChangeLog instance);
    #endregion
		
		public dbDataContext() : 
				base(global::WeixinRoboot.Properties.Settings.Default.WeinxinRobootConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<aspnet_Users> aspnet_Users
		{
			get
			{
				return this.GetTable<aspnet_Users>();
			}
		}
		
		public System.Data.Linq.Table<aspnet_Membership> aspnet_Membership
		{
			get
			{
				return this.GetTable<aspnet_Membership>();
			}
		}
		
		public System.Data.Linq.Table<WX_UserReply> WX_UserReply
		{
			get
			{
				return this.GetTable<WX_UserReply>();
			}
		}
		
		public System.Data.Linq.Table<Game_ChongqingshishicaiPeriodMinute> Game_ChongqingshishicaiPeriodMinute
		{
			get
			{
				return this.GetTable<Game_ChongqingshishicaiPeriodMinute>();
			}
		}
		
		public System.Data.Linq.Table<Game_BasicRatio> Game_BasicRatio
		{
			get
			{
				return this.GetTable<Game_BasicRatio>();
			}
		}
		
		public System.Data.Linq.Table<WX_UserReplyLog> WX_UserReplyLog
		{
			get
			{
				return this.GetTable<WX_UserReplyLog>();
			}
		}
		
		public System.Data.Linq.Table<Game_Result> Game_Result
		{
			get
			{
				return this.GetTable<Game_Result>();
			}
		}
		
		public System.Data.Linq.Table<aspnet_UsersNewGameResultSend> aspnet_UsersNewGameResultSend
		{
			get
			{
				return this.GetTable<aspnet_UsersNewGameResultSend>();
			}
		}
		
		public System.Data.Linq.Table<WX_UserGameLog> WX_UserGameLog
		{
			get
			{
				return this.GetTable<WX_UserGameLog>();
			}
		}
		
		public System.Data.Linq.Table<WX_UserChangeLog> WX_UserChangeLog
		{
			get
			{
				return this.GetTable<WX_UserChangeLog>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Logic_WX_UserGameLog_Deal")]
		public ISingleResult<Logic_WX_UserGameLog_DealResult> Logic_WX_UserGameLog_Deal([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> aspnet_UserID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aspnet_UserID);
			return ((ISingleResult<Logic_WX_UserGameLog_DealResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Logic_WX_UserReplyLog_MySendCreate")]
		public void Logic_WX_UserReplyLog_MySendCreate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Content", DbType="NVarChar(4000)")] string content, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ToWXUserName", DbType="NVarChar(50)")] string toWXUserName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> aspnet_UserID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReplyTime", DbType="DateTime")] System.Nullable<System.DateTime> replyTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(MAX)")] ref string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), content, toWXUserName, aspnet_UserID, replyTime, message);
			message = ((string)(result.GetParameterValue(4)));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Logic_WX_UserReplyLog_Create")]
		public void Logic_WX_UserReplyLog_Create([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Content", DbType="NVarChar(4000)")] string content, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FromWXUserName", DbType="NVarChar(50)")] string fromWXUserName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="UniqueIdentifier")] System.Nullable<System.Guid> aspnet_UserID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiveTime", DbType="DateTime")] System.Nullable<System.DateTime> receiveTime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(MAX)")] ref string message, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SourceType", DbType="NVarChar(50)")] string sourceType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), content, fromWXUserName, aspnet_UserID, receiveTime, message, sourceType);
			message = ((string)(result.GetParameterValue(4)));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Users")]
	public partial class aspnet_Users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _UserId;
		
		private string _UserName;
		
		private string _LoweredUserName;
		
		private string _MobileAlias;
		
		private bool _IsAnonymous;
		
		private System.DateTime _LastActivityDate;
		
		private EntityRef<aspnet_Membership> _aspnet_Membership;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnLoweredUserNameChanging(string value);
    partial void OnLoweredUserNameChanged();
    partial void OnMobileAliasChanging(string value);
    partial void OnMobileAliasChanged();
    partial void OnIsAnonymousChanging(bool value);
    partial void OnIsAnonymousChanged();
    partial void OnLastActivityDateChanging(System.DateTime value);
    partial void OnLastActivityDateChanged();
    #endregion
		
		public aspnet_Users()
		{
			this._aspnet_Membership = default(EntityRef<aspnet_Membership>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredUserName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string LoweredUserName
		{
			get
			{
				return this._LoweredUserName;
			}
			set
			{
				if ((this._LoweredUserName != value))
				{
					this.OnLoweredUserNameChanging(value);
					this.SendPropertyChanging();
					this._LoweredUserName = value;
					this.SendPropertyChanged("LoweredUserName");
					this.OnLoweredUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileAlias", DbType="NVarChar(16)")]
		public string MobileAlias
		{
			get
			{
				return this._MobileAlias;
			}
			set
			{
				if ((this._MobileAlias != value))
				{
					this.OnMobileAliasChanging(value);
					this.SendPropertyChanging();
					this._MobileAlias = value;
					this.SendPropertyChanged("MobileAlias");
					this.OnMobileAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAnonymous", DbType="Bit NOT NULL")]
		public bool IsAnonymous
		{
			get
			{
				return this._IsAnonymous;
			}
			set
			{
				if ((this._IsAnonymous != value))
				{
					this.OnIsAnonymousChanging(value);
					this.SendPropertyChanging();
					this._IsAnonymous = value;
					this.SendPropertyChanged("IsAnonymous");
					this.OnIsAnonymousChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				if ((this._LastActivityDate != value))
				{
					this.OnLastActivityDateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDate = value;
					this.SendPropertyChanged("LastActivityDate");
					this.OnLastActivityDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Users_aspnet_Membership", Storage="_aspnet_Membership", ThisKey="UserId", OtherKey="UserId", IsUnique=true, IsForeignKey=false)]
		public aspnet_Membership aspnet_Membership
		{
			get
			{
				return this._aspnet_Membership.Entity;
			}
			set
			{
				aspnet_Membership previousValue = this._aspnet_Membership.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_Membership.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_Membership.Entity = null;
						previousValue.aspnet_Users = null;
					}
					this._aspnet_Membership.Entity = value;
					if ((value != null))
					{
						value.aspnet_Users = this;
					}
					this.SendPropertyChanged("aspnet_Membership");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_Membership")]
	public partial class aspnet_Membership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ApplicationId;
		
		private System.Guid _UserId;
		
		private string _Password;
		
		private int _PasswordFormat;
		
		private string _PasswordSalt;
		
		private string _MobilePIN;
		
		private string _Email;
		
		private string _LoweredEmail;
		
		private string _PasswordQuestion;
		
		private string _PasswordAnswer;
		
		private bool _IsApproved;
		
		private bool _IsLockedOut;
		
		private System.DateTime _CreateDate;
		
		private System.DateTime _LastLoginDate;
		
		private System.DateTime _LastPasswordChangedDate;
		
		private System.DateTime _LastLockoutDate;
		
		private int _FailedPasswordAttemptCount;
		
		private System.DateTime _FailedPasswordAttemptWindowStart;
		
		private int _FailedPasswordAnswerAttemptCount;
		
		private System.DateTime _FailedPasswordAnswerAttemptWindowStart;
		
		private string _Comment;
		
		private EntityRef<aspnet_Users> _aspnet_Users;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnApplicationIdChanging(System.Guid value);
    partial void OnApplicationIdChanged();
    partial void OnUserIdChanging(System.Guid value);
    partial void OnUserIdChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordFormatChanging(int value);
    partial void OnPasswordFormatChanged();
    partial void OnPasswordSaltChanging(string value);
    partial void OnPasswordSaltChanged();
    partial void OnMobilePINChanging(string value);
    partial void OnMobilePINChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnLoweredEmailChanging(string value);
    partial void OnLoweredEmailChanged();
    partial void OnPasswordQuestionChanging(string value);
    partial void OnPasswordQuestionChanged();
    partial void OnPasswordAnswerChanging(string value);
    partial void OnPasswordAnswerChanged();
    partial void OnIsApprovedChanging(bool value);
    partial void OnIsApprovedChanged();
    partial void OnIsLockedOutChanging(bool value);
    partial void OnIsLockedOutChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnLastLoginDateChanging(System.DateTime value);
    partial void OnLastLoginDateChanged();
    partial void OnLastPasswordChangedDateChanging(System.DateTime value);
    partial void OnLastPasswordChangedDateChanged();
    partial void OnLastLockoutDateChanging(System.DateTime value);
    partial void OnLastLockoutDateChanged();
    partial void OnFailedPasswordAttemptCountChanging(int value);
    partial void OnFailedPasswordAttemptCountChanged();
    partial void OnFailedPasswordAttemptWindowStartChanging(System.DateTime value);
    partial void OnFailedPasswordAttemptWindowStartChanged();
    partial void OnFailedPasswordAnswerAttemptCountChanging(int value);
    partial void OnFailedPasswordAnswerAttemptCountChanged();
    partial void OnFailedPasswordAnswerAttemptWindowStartChanging(System.DateTime value);
    partial void OnFailedPasswordAnswerAttemptWindowStartChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    #endregion
		
		public aspnet_Membership()
		{
			this._aspnet_Users = default(EntityRef<aspnet_Users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApplicationId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ApplicationId
		{
			get
			{
				return this._ApplicationId;
			}
			set
			{
				if ((this._ApplicationId != value))
				{
					this.OnApplicationIdChanging(value);
					this.SendPropertyChanging();
					this._ApplicationId = value;
					this.SendPropertyChanged("ApplicationId");
					this.OnApplicationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					if (this._aspnet_Users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordFormat", DbType="Int NOT NULL")]
		public int PasswordFormat
		{
			get
			{
				return this._PasswordFormat;
			}
			set
			{
				if ((this._PasswordFormat != value))
				{
					this.OnPasswordFormatChanging(value);
					this.SendPropertyChanging();
					this._PasswordFormat = value;
					this.SendPropertyChanged("PasswordFormat");
					this.OnPasswordFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordSalt", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string PasswordSalt
		{
			get
			{
				return this._PasswordSalt;
			}
			set
			{
				if ((this._PasswordSalt != value))
				{
					this.OnPasswordSaltChanging(value);
					this.SendPropertyChanging();
					this._PasswordSalt = value;
					this.SendPropertyChanged("PasswordSalt");
					this.OnPasswordSaltChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobilePIN", DbType="NVarChar(16)")]
		public string MobilePIN
		{
			get
			{
				return this._MobilePIN;
			}
			set
			{
				if ((this._MobilePIN != value))
				{
					this.OnMobilePINChanging(value);
					this.SendPropertyChanging();
					this._MobilePIN = value;
					this.SendPropertyChanged("MobilePIN");
					this.OnMobilePINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(256)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoweredEmail", DbType="NVarChar(256)")]
		public string LoweredEmail
		{
			get
			{
				return this._LoweredEmail;
			}
			set
			{
				if ((this._LoweredEmail != value))
				{
					this.OnLoweredEmailChanging(value);
					this.SendPropertyChanging();
					this._LoweredEmail = value;
					this.SendPropertyChanged("LoweredEmail");
					this.OnLoweredEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordQuestion", DbType="NVarChar(256)")]
		public string PasswordQuestion
		{
			get
			{
				return this._PasswordQuestion;
			}
			set
			{
				if ((this._PasswordQuestion != value))
				{
					this.OnPasswordQuestionChanging(value);
					this.SendPropertyChanging();
					this._PasswordQuestion = value;
					this.SendPropertyChanged("PasswordQuestion");
					this.OnPasswordQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAnswer", DbType="NVarChar(128)")]
		public string PasswordAnswer
		{
			get
			{
				return this._PasswordAnswer;
			}
			set
			{
				if ((this._PasswordAnswer != value))
				{
					this.OnPasswordAnswerChanging(value);
					this.SendPropertyChanging();
					this._PasswordAnswer = value;
					this.SendPropertyChanged("PasswordAnswer");
					this.OnPasswordAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsApproved", DbType="Bit NOT NULL")]
		public bool IsApproved
		{
			get
			{
				return this._IsApproved;
			}
			set
			{
				if ((this._IsApproved != value))
				{
					this.OnIsApprovedChanging(value);
					this.SendPropertyChanging();
					this._IsApproved = value;
					this.SendPropertyChanged("IsApproved");
					this.OnIsApprovedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLockedOut", DbType="Bit NOT NULL")]
		public bool IsLockedOut
		{
			get
			{
				return this._IsLockedOut;
			}
			set
			{
				if ((this._IsLockedOut != value))
				{
					this.OnIsLockedOutChanging(value);
					this.SendPropertyChanging();
					this._IsLockedOut = value;
					this.SendPropertyChanged("IsLockedOut");
					this.OnIsLockedOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoginDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastLoginDate
		{
			get
			{
				return this._LastLoginDate;
			}
			set
			{
				if ((this._LastLoginDate != value))
				{
					this.OnLastLoginDateChanging(value);
					this.SendPropertyChanging();
					this._LastLoginDate = value;
					this.SendPropertyChanged("LastLoginDate");
					this.OnLastLoginDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastPasswordChangedDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastPasswordChangedDate
		{
			get
			{
				return this._LastPasswordChangedDate;
			}
			set
			{
				if ((this._LastPasswordChangedDate != value))
				{
					this.OnLastPasswordChangedDateChanging(value);
					this.SendPropertyChanging();
					this._LastPasswordChangedDate = value;
					this.SendPropertyChanged("LastPasswordChangedDate");
					this.OnLastPasswordChangedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLockoutDate", DbType="DateTime NOT NULL")]
		public System.DateTime LastLockoutDate
		{
			get
			{
				return this._LastLockoutDate;
			}
			set
			{
				if ((this._LastLockoutDate != value))
				{
					this.OnLastLockoutDateChanging(value);
					this.SendPropertyChanging();
					this._LastLockoutDate = value;
					this.SendPropertyChanged("LastLockoutDate");
					this.OnLastLockoutDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptCount", DbType="Int NOT NULL")]
		public int FailedPasswordAttemptCount
		{
			get
			{
				return this._FailedPasswordAttemptCount;
			}
			set
			{
				if ((this._FailedPasswordAttemptCount != value))
				{
					this.OnFailedPasswordAttemptCountChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAttemptCount = value;
					this.SendPropertyChanged("FailedPasswordAttemptCount");
					this.OnFailedPasswordAttemptCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAttemptWindowStart", DbType="DateTime NOT NULL")]
		public System.DateTime FailedPasswordAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAttemptWindowStart;
			}
			set
			{
				if ((this._FailedPasswordAttemptWindowStart != value))
				{
					this.OnFailedPasswordAttemptWindowStartChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAttemptWindowStart = value;
					this.SendPropertyChanged("FailedPasswordAttemptWindowStart");
					this.OnFailedPasswordAttemptWindowStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptCount", DbType="Int NOT NULL")]
		public int FailedPasswordAnswerAttemptCount
		{
			get
			{
				return this._FailedPasswordAnswerAttemptCount;
			}
			set
			{
				if ((this._FailedPasswordAnswerAttemptCount != value))
				{
					this.OnFailedPasswordAnswerAttemptCountChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAnswerAttemptCount = value;
					this.SendPropertyChanged("FailedPasswordAnswerAttemptCount");
					this.OnFailedPasswordAnswerAttemptCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FailedPasswordAnswerAttemptWindowStart", DbType="DateTime NOT NULL")]
		public System.DateTime FailedPasswordAnswerAttemptWindowStart
		{
			get
			{
				return this._FailedPasswordAnswerAttemptWindowStart;
			}
			set
			{
				if ((this._FailedPasswordAnswerAttemptWindowStart != value))
				{
					this.OnFailedPasswordAnswerAttemptWindowStartChanging(value);
					this.SendPropertyChanging();
					this._FailedPasswordAnswerAttemptWindowStart = value;
					this.SendPropertyChanged("FailedPasswordAnswerAttemptWindowStart");
					this.OnFailedPasswordAnswerAttemptWindowStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="aspnet_Users_aspnet_Membership", Storage="_aspnet_Users", ThisKey="UserId", OtherKey="UserId", IsForeignKey=true)]
		public aspnet_Users aspnet_Users
		{
			get
			{
				return this._aspnet_Users.Entity;
			}
			set
			{
				aspnet_Users previousValue = this._aspnet_Users.Entity;
				if (((previousValue != value) 
							|| (this._aspnet_Users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._aspnet_Users.Entity = null;
						previousValue.aspnet_Membership = null;
					}
					this._aspnet_Users.Entity = value;
					if ((value != null))
					{
						value.aspnet_Membership = this;
						this._UserId = value.UserId;
					}
					else
					{
						this._UserId = default(System.Guid);
					}
					this.SendPropertyChanged("aspnet_Users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_UserReply")]
	public partial class WX_UserReply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WX_UserName;
		
		private System.Nullable<bool> _IsReply;
		
		private System.Guid _aspnet_UserID;
		
		private string _NickName;
		
		private string _RemarkName;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWX_UserNameChanging(string value);
    partial void OnWX_UserNameChanged();
    partial void OnIsReplyChanging(System.Nullable<bool> value);
    partial void OnIsReplyChanged();
    partial void Onaspnet_UserIDChanging(System.Guid value);
    partial void Onaspnet_UserIDChanged();
    partial void OnNickNameChanging(string value);
    partial void OnNickNameChanged();
    partial void OnRemarkNameChanging(string value);
    partial void OnRemarkNameChanged();
    #endregion
		
		public WX_UserReply()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WX_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WX_UserName
		{
			get
			{
				return this._WX_UserName;
			}
			set
			{
				if ((this._WX_UserName != value))
				{
					this.OnWX_UserNameChanging(value);
					this.SendPropertyChanging();
					this._WX_UserName = value;
					this.SendPropertyChanged("WX_UserName");
					this.OnWX_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsReply", DbType="Bit")]
		public System.Nullable<bool> IsReply
		{
			get
			{
				return this._IsReply;
			}
			set
			{
				if ((this._IsReply != value))
				{
					this.OnIsReplyChanging(value);
					this.SendPropertyChanging();
					this._IsReply = value;
					this.SendPropertyChanged("IsReply");
					this.OnIsReplyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid aspnet_UserID
		{
			get
			{
				return this._aspnet_UserID;
			}
			set
			{
				if ((this._aspnet_UserID != value))
				{
					this.Onaspnet_UserIDChanging(value);
					this.SendPropertyChanging();
					this._aspnet_UserID = value;
					this.SendPropertyChanged("aspnet_UserID");
					this.Onaspnet_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NickName", DbType="NVarChar(512)")]
		public string NickName
		{
			get
			{
				return this._NickName;
			}
			set
			{
				if ((this._NickName != value))
				{
					this.OnNickNameChanging(value);
					this.SendPropertyChanging();
					this._NickName = value;
					this.SendPropertyChanged("NickName");
					this.OnNickNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkName", DbType="NVarChar(512)")]
		public string RemarkName
		{
			get
			{
				return this._RemarkName;
			}
			set
			{
				if ((this._RemarkName != value))
				{
					this.OnRemarkNameChanging(value);
					this.SendPropertyChanging();
					this._RemarkName = value;
					this.SendPropertyChanged("RemarkName");
					this.OnRemarkNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Game_ChongqingshishicaiPeriodMinute")]
	public partial class Game_ChongqingshishicaiPeriodMinute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GameType;
		
		private string _PeriodIndex;
		
		private string _TimeMinute;
		
		private string _Private_Period;
		
		private System.Nullable<int> _Private_day;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGameTypeChanging(string value);
    partial void OnGameTypeChanged();
    partial void OnPeriodIndexChanging(string value);
    partial void OnPeriodIndexChanged();
    partial void OnTimeMinuteChanging(string value);
    partial void OnTimeMinuteChanged();
    partial void OnPrivate_PeriodChanging(string value);
    partial void OnPrivate_PeriodChanged();
    partial void OnPrivate_dayChanging(System.Nullable<int> value);
    partial void OnPrivate_dayChanged();
    #endregion
		
		public Game_ChongqingshishicaiPeriodMinute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GameType
		{
			get
			{
				return this._GameType;
			}
			set
			{
				if ((this._GameType != value))
				{
					this.OnGameTypeChanging(value);
					this.SendPropertyChanging();
					this._GameType = value;
					this.SendPropertyChanged("GameType");
					this.OnGameTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodIndex", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PeriodIndex
		{
			get
			{
				return this._PeriodIndex;
			}
			set
			{
				if ((this._PeriodIndex != value))
				{
					this.OnPeriodIndexChanging(value);
					this.SendPropertyChanging();
					this._PeriodIndex = value;
					this.SendPropertyChanged("PeriodIndex");
					this.OnPeriodIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeMinute", DbType="NVarChar(50)")]
		public string TimeMinute
		{
			get
			{
				return this._TimeMinute;
			}
			set
			{
				if ((this._TimeMinute != value))
				{
					this.OnTimeMinuteChanging(value);
					this.SendPropertyChanging();
					this._TimeMinute = value;
					this.SendPropertyChanged("TimeMinute");
					this.OnTimeMinuteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Private_Period", DbType="NVarChar(50)")]
		public string Private_Period
		{
			get
			{
				return this._Private_Period;
			}
			set
			{
				if ((this._Private_Period != value))
				{
					this.OnPrivate_PeriodChanging(value);
					this.SendPropertyChanging();
					this._Private_Period = value;
					this.SendPropertyChanged("Private_Period");
					this.OnPrivate_PeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Private_day", DbType="Int")]
		public System.Nullable<int> Private_day
		{
			get
			{
				return this._Private_day;
			}
			set
			{
				if ((this._Private_day != value))
				{
					this.OnPrivate_dayChanging(value);
					this.SendPropertyChanging();
					this._Private_day = value;
					this.SendPropertyChanged("Private_day");
					this.OnPrivate_dayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Game_BasicRatio")]
	public partial class Game_BasicRatio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _aspnet_UserID;
		
		private string _GameType;
		
		private string _BuyType;
		
		private string _BuyValue;
		
		private decimal _MinBuy;
		
		private decimal _MaxBuy;
		
		private System.Nullable<decimal> _BasicRatio;
		
		private System.Nullable<decimal> _OrderIndex;
		
		private System.Nullable<bool> _IncludeMin;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onaspnet_UserIDChanging(System.Guid value);
    partial void Onaspnet_UserIDChanged();
    partial void OnGameTypeChanging(string value);
    partial void OnGameTypeChanged();
    partial void OnBuyTypeChanging(string value);
    partial void OnBuyTypeChanged();
    partial void OnBuyValueChanging(string value);
    partial void OnBuyValueChanged();
    partial void OnMinBuyChanging(decimal value);
    partial void OnMinBuyChanged();
    partial void OnMaxBuyChanging(decimal value);
    partial void OnMaxBuyChanged();
    partial void OnBasicRatioChanging(System.Nullable<decimal> value);
    partial void OnBasicRatioChanged();
    partial void OnOrderIndexChanging(System.Nullable<decimal> value);
    partial void OnOrderIndexChanged();
    partial void OnIncludeMinChanging(System.Nullable<bool> value);
    partial void OnIncludeMinChanged();
    #endregion
		
		public Game_BasicRatio()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid aspnet_UserID
		{
			get
			{
				return this._aspnet_UserID;
			}
			set
			{
				if ((this._aspnet_UserID != value))
				{
					this.Onaspnet_UserIDChanging(value);
					this.SendPropertyChanging();
					this._aspnet_UserID = value;
					this.SendPropertyChanged("aspnet_UserID");
					this.Onaspnet_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GameType
		{
			get
			{
				return this._GameType;
			}
			set
			{
				if ((this._GameType != value))
				{
					this.OnGameTypeChanging(value);
					this.SendPropertyChanging();
					this._GameType = value;
					this.SendPropertyChanged("GameType");
					this.OnGameTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyType", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BuyType
		{
			get
			{
				return this._BuyType;
			}
			set
			{
				if ((this._BuyType != value))
				{
					this.OnBuyTypeChanging(value);
					this.SendPropertyChanging();
					this._BuyType = value;
					this.SendPropertyChanged("BuyType");
					this.OnBuyTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyValue", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BuyValue
		{
			get
			{
				return this._BuyValue;
			}
			set
			{
				if ((this._BuyValue != value))
				{
					this.OnBuyValueChanging(value);
					this.SendPropertyChanging();
					this._BuyValue = value;
					this.SendPropertyChanged("BuyValue");
					this.OnBuyValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinBuy", DbType="Decimal(18,3) NOT NULL", IsPrimaryKey=true)]
		public decimal MinBuy
		{
			get
			{
				return this._MinBuy;
			}
			set
			{
				if ((this._MinBuy != value))
				{
					this.OnMinBuyChanging(value);
					this.SendPropertyChanging();
					this._MinBuy = value;
					this.SendPropertyChanged("MinBuy");
					this.OnMinBuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxBuy", DbType="Decimal(18,3) NOT NULL", IsPrimaryKey=true)]
		public decimal MaxBuy
		{
			get
			{
				return this._MaxBuy;
			}
			set
			{
				if ((this._MaxBuy != value))
				{
					this.OnMaxBuyChanging(value);
					this.SendPropertyChanging();
					this._MaxBuy = value;
					this.SendPropertyChanged("MaxBuy");
					this.OnMaxBuyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicRatio", DbType="Decimal(18,3)")]
		public System.Nullable<decimal> BasicRatio
		{
			get
			{
				return this._BasicRatio;
			}
			set
			{
				if ((this._BasicRatio != value))
				{
					this.OnBasicRatioChanging(value);
					this.SendPropertyChanging();
					this._BasicRatio = value;
					this.SendPropertyChanged("BasicRatio");
					this.OnBasicRatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderIndex", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> OrderIndex
		{
			get
			{
				return this._OrderIndex;
			}
			set
			{
				if ((this._OrderIndex != value))
				{
					this.OnOrderIndexChanging(value);
					this.SendPropertyChanging();
					this._OrderIndex = value;
					this.SendPropertyChanged("OrderIndex");
					this.OnOrderIndexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IncludeMin", DbType="Bit")]
		public System.Nullable<bool> IncludeMin
		{
			get
			{
				return this._IncludeMin;
			}
			set
			{
				if ((this._IncludeMin != value))
				{
					this.OnIncludeMinChanging(value);
					this.SendPropertyChanging();
					this._IncludeMin = value;
					this.SendPropertyChanged("IncludeMin");
					this.OnIncludeMinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_UserReplyLog")]
	public partial class WX_UserReplyLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WX_UserName;
		
		private System.Guid _aspnet_UserID;
		
		private System.DateTime _ReceiveTime;
		
		private string _ReceiveContent;
		
		private string _ReplyContent;
		
		private System.Nullable<System.DateTime> _ReplyTime;
		
		private System.Nullable<bool> _HaveDeal;
		
		private string _SourceType;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWX_UserNameChanging(string value);
    partial void OnWX_UserNameChanged();
    partial void Onaspnet_UserIDChanging(System.Guid value);
    partial void Onaspnet_UserIDChanged();
    partial void OnReceiveTimeChanging(System.DateTime value);
    partial void OnReceiveTimeChanged();
    partial void OnReceiveContentChanging(string value);
    partial void OnReceiveContentChanged();
    partial void OnReplyContentChanging(string value);
    partial void OnReplyContentChanged();
    partial void OnReplyTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnReplyTimeChanged();
    partial void OnHaveDealChanging(System.Nullable<bool> value);
    partial void OnHaveDealChanged();
    partial void OnSourceTypeChanging(string value);
    partial void OnSourceTypeChanged();
    #endregion
		
		public WX_UserReplyLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WX_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WX_UserName
		{
			get
			{
				return this._WX_UserName;
			}
			set
			{
				if ((this._WX_UserName != value))
				{
					this.OnWX_UserNameChanging(value);
					this.SendPropertyChanging();
					this._WX_UserName = value;
					this.SendPropertyChanged("WX_UserName");
					this.OnWX_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid aspnet_UserID
		{
			get
			{
				return this._aspnet_UserID;
			}
			set
			{
				if ((this._aspnet_UserID != value))
				{
					this.Onaspnet_UserIDChanging(value);
					this.SendPropertyChanging();
					this._aspnet_UserID = value;
					this.SendPropertyChanged("aspnet_UserID");
					this.Onaspnet_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiveTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ReceiveTime
		{
			get
			{
				return this._ReceiveTime;
			}
			set
			{
				if ((this._ReceiveTime != value))
				{
					this.OnReceiveTimeChanging(value);
					this.SendPropertyChanging();
					this._ReceiveTime = value;
					this.SendPropertyChanged("ReceiveTime");
					this.OnReceiveTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiveContent", DbType="NVarChar(4000)")]
		public string ReceiveContent
		{
			get
			{
				return this._ReceiveContent;
			}
			set
			{
				if ((this._ReceiveContent != value))
				{
					this.OnReceiveContentChanging(value);
					this.SendPropertyChanging();
					this._ReceiveContent = value;
					this.SendPropertyChanged("ReceiveContent");
					this.OnReceiveContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyContent", DbType="NVarChar(4000)")]
		public string ReplyContent
		{
			get
			{
				return this._ReplyContent;
			}
			set
			{
				if ((this._ReplyContent != value))
				{
					this.OnReplyContentChanging(value);
					this.SendPropertyChanging();
					this._ReplyContent = value;
					this.SendPropertyChanged("ReplyContent");
					this.OnReplyContentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplyTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> ReplyTime
		{
			get
			{
				return this._ReplyTime;
			}
			set
			{
				if ((this._ReplyTime != value))
				{
					this.OnReplyTimeChanging(value);
					this.SendPropertyChanging();
					this._ReplyTime = value;
					this.SendPropertyChanged("ReplyTime");
					this.OnReplyTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveDeal", DbType="Bit")]
		public System.Nullable<bool> HaveDeal
		{
			get
			{
				return this._HaveDeal;
			}
			set
			{
				if ((this._HaveDeal != value))
				{
					this.OnHaveDealChanging(value);
					this.SendPropertyChanging();
					this._HaveDeal = value;
					this.SendPropertyChanged("HaveDeal");
					this.OnHaveDealChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SourceType", DbType="NVarChar(5)")]
		public string SourceType
		{
			get
			{
				return this._SourceType;
			}
			set
			{
				if ((this._SourceType != value))
				{
					this.OnSourceTypeChanging(value);
					this.SendPropertyChanging();
					this._SourceType = value;
					this.SendPropertyChanged("SourceType");
					this.OnSourceTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Game_Result")]
	public partial class Game_Result : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _GameName;
		
		private string _GamePeriod;
		
		private string _GameResult;
		
		private System.Nullable<System.DateTime> _GameTime;
		
		private System.Nullable<int> _NumTotal;
		
		private string _BigSmall;
		
		private string _SingleDouble;
		
		private string _DragonTiger;
		
		private string _GamePrivatePeriod;
		
		private System.Guid _aspnet_UserID;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGameNameChanging(string value);
    partial void OnGameNameChanged();
    partial void OnGamePeriodChanging(string value);
    partial void OnGamePeriodChanged();
    partial void OnGameResultChanging(string value);
    partial void OnGameResultChanged();
    partial void OnGameTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnGameTimeChanged();
    partial void OnNumTotalChanging(System.Nullable<int> value);
    partial void OnNumTotalChanged();
    partial void OnBigSmallChanging(string value);
    partial void OnBigSmallChanged();
    partial void OnSingleDoubleChanging(string value);
    partial void OnSingleDoubleChanged();
    partial void OnDragonTigerChanging(string value);
    partial void OnDragonTigerChanged();
    partial void OnGamePrivatePeriodChanging(string value);
    partial void OnGamePrivatePeriodChanged();
    partial void Onaspnet_UserIDChanging(System.Guid value);
    partial void Onaspnet_UserIDChanged();
    #endregion
		
		public Game_Result()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GameName
		{
			get
			{
				return this._GameName;
			}
			set
			{
				if ((this._GameName != value))
				{
					this.OnGameNameChanging(value);
					this.SendPropertyChanging();
					this._GameName = value;
					this.SendPropertyChanged("GameName");
					this.OnGameNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GamePeriod", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GamePeriod
		{
			get
			{
				return this._GamePeriod;
			}
			set
			{
				if ((this._GamePeriod != value))
				{
					this.OnGamePeriodChanging(value);
					this.SendPropertyChanging();
					this._GamePeriod = value;
					this.SendPropertyChanged("GamePeriod");
					this.OnGamePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameResult", DbType="NVarChar(100)")]
		public string GameResult
		{
			get
			{
				return this._GameResult;
			}
			set
			{
				if ((this._GameResult != value))
				{
					this.OnGameResultChanging(value);
					this.SendPropertyChanging();
					this._GameResult = value;
					this.SendPropertyChanged("GameResult");
					this.OnGameResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> GameTime
		{
			get
			{
				return this._GameTime;
			}
			set
			{
				if ((this._GameTime != value))
				{
					this.OnGameTimeChanging(value);
					this.SendPropertyChanging();
					this._GameTime = value;
					this.SendPropertyChanged("GameTime");
					this.OnGameTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumTotal", DbType="Int")]
		public System.Nullable<int> NumTotal
		{
			get
			{
				return this._NumTotal;
			}
			set
			{
				if ((this._NumTotal != value))
				{
					this.OnNumTotalChanging(value);
					this.SendPropertyChanging();
					this._NumTotal = value;
					this.SendPropertyChanged("NumTotal");
					this.OnNumTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BigSmall", DbType="NVarChar(5)")]
		public string BigSmall
		{
			get
			{
				return this._BigSmall;
			}
			set
			{
				if ((this._BigSmall != value))
				{
					this.OnBigSmallChanging(value);
					this.SendPropertyChanging();
					this._BigSmall = value;
					this.SendPropertyChanged("BigSmall");
					this.OnBigSmallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SingleDouble", DbType="NVarChar(5)")]
		public string SingleDouble
		{
			get
			{
				return this._SingleDouble;
			}
			set
			{
				if ((this._SingleDouble != value))
				{
					this.OnSingleDoubleChanging(value);
					this.SendPropertyChanging();
					this._SingleDouble = value;
					this.SendPropertyChanged("SingleDouble");
					this.OnSingleDoubleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DragonTiger", DbType="NVarChar(5)")]
		public string DragonTiger
		{
			get
			{
				return this._DragonTiger;
			}
			set
			{
				if ((this._DragonTiger != value))
				{
					this.OnDragonTigerChanging(value);
					this.SendPropertyChanging();
					this._DragonTiger = value;
					this.SendPropertyChanged("DragonTiger");
					this.OnDragonTigerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GamePrivatePeriod", DbType="NVarChar(50)")]
		public string GamePrivatePeriod
		{
			get
			{
				return this._GamePrivatePeriod;
			}
			set
			{
				if ((this._GamePrivatePeriod != value))
				{
					this.OnGamePrivatePeriodChanging(value);
					this.SendPropertyChanging();
					this._GamePrivatePeriod = value;
					this.SendPropertyChanged("GamePrivatePeriod");
					this.OnGamePrivatePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid aspnet_UserID
		{
			get
			{
				return this._aspnet_UserID;
			}
			set
			{
				if ((this._aspnet_UserID != value))
				{
					this.Onaspnet_UserIDChanging(value);
					this.SendPropertyChanging();
					this._aspnet_UserID = value;
					this.SendPropertyChanged("aspnet_UserID");
					this.Onaspnet_UserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.aspnet_UsersNewGameResultSend")]
	public partial class aspnet_UsersNewGameResultSend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _aspnet_UserID;
		
		private System.Nullable<bool> _IsNewSend;
		
		private string _ActiveCode;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onaspnet_UserIDChanging(System.Guid value);
    partial void Onaspnet_UserIDChanged();
    partial void OnIsNewSendChanging(System.Nullable<bool> value);
    partial void OnIsNewSendChanged();
    partial void OnActiveCodeChanging(string value);
    partial void OnActiveCodeChanged();
    #endregion
		
		public aspnet_UsersNewGameResultSend()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid aspnet_UserID
		{
			get
			{
				return this._aspnet_UserID;
			}
			set
			{
				if ((this._aspnet_UserID != value))
				{
					this.Onaspnet_UserIDChanging(value);
					this.SendPropertyChanging();
					this._aspnet_UserID = value;
					this.SendPropertyChanged("aspnet_UserID");
					this.Onaspnet_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsNewSend", DbType="Bit")]
		public System.Nullable<bool> IsNewSend
		{
			get
			{
				return this._IsNewSend;
			}
			set
			{
				if ((this._IsNewSend != value))
				{
					this.OnIsNewSendChanging(value);
					this.SendPropertyChanging();
					this._IsNewSend = value;
					this.SendPropertyChanged("IsNewSend");
					this.OnIsNewSendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActiveCode", DbType="NVarChar(4000)")]
		public string ActiveCode
		{
			get
			{
				return this._ActiveCode;
			}
			set
			{
				if ((this._ActiveCode != value))
				{
					this.OnActiveCodeChanging(value);
					this.SendPropertyChanging();
					this._ActiveCode = value;
					this.SendPropertyChanged("ActiveCode");
					this.OnActiveCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_UserGameLog")]
	public partial class WX_UserGameLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WX_UserName;
		
		private System.Guid _aspnet_UserID;
		
		private System.DateTime _TransTime;
		
		private string _GameName;
		
		private string _GamePeriod;
		
		private string _GameResult;
		
		private System.Nullable<int> _Gr_NumTotal;
		
		private string _Gr_BigSmall;
		
		private string _Gr_SingleDouble;
		
		private string _Gr_DragonTiger;
		
		private string _Buy_Type;
		
		private string _Buy_Value;
		
		private System.Nullable<decimal> _Buy_Ratio;
		
		private System.Nullable<decimal> _Buy_Point;
		
		private System.Nullable<decimal> _Result_Point;
		
		private System.Nullable<bool> _Result_HaveProcess;
		
		private string _GameLocalPeriod;
		
		private System.Nullable<System.DateTime> _GP_LastModify;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWX_UserNameChanging(string value);
    partial void OnWX_UserNameChanged();
    partial void Onaspnet_UserIDChanging(System.Guid value);
    partial void Onaspnet_UserIDChanged();
    partial void OnTransTimeChanging(System.DateTime value);
    partial void OnTransTimeChanged();
    partial void OnGameNameChanging(string value);
    partial void OnGameNameChanged();
    partial void OnGamePeriodChanging(string value);
    partial void OnGamePeriodChanged();
    partial void OnGameResultChanging(string value);
    partial void OnGameResultChanged();
    partial void OnGr_NumTotalChanging(System.Nullable<int> value);
    partial void OnGr_NumTotalChanged();
    partial void OnGr_BigSmallChanging(string value);
    partial void OnGr_BigSmallChanged();
    partial void OnGr_SingleDoubleChanging(string value);
    partial void OnGr_SingleDoubleChanged();
    partial void OnGr_DragonTigerChanging(string value);
    partial void OnGr_DragonTigerChanged();
    partial void OnBuy_TypeChanging(string value);
    partial void OnBuy_TypeChanged();
    partial void OnBuy_ValueChanging(string value);
    partial void OnBuy_ValueChanged();
    partial void OnBuy_RatioChanging(System.Nullable<decimal> value);
    partial void OnBuy_RatioChanged();
    partial void OnBuy_PointChanging(System.Nullable<decimal> value);
    partial void OnBuy_PointChanged();
    partial void OnResult_PointChanging(System.Nullable<decimal> value);
    partial void OnResult_PointChanged();
    partial void OnResult_HaveProcessChanging(System.Nullable<bool> value);
    partial void OnResult_HaveProcessChanged();
    partial void OnGameLocalPeriodChanging(string value);
    partial void OnGameLocalPeriodChanged();
    partial void OnGP_LastModifyChanging(System.Nullable<System.DateTime> value);
    partial void OnGP_LastModifyChanged();
    #endregion
		
		public WX_UserGameLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WX_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WX_UserName
		{
			get
			{
				return this._WX_UserName;
			}
			set
			{
				if ((this._WX_UserName != value))
				{
					this.OnWX_UserNameChanging(value);
					this.SendPropertyChanging();
					this._WX_UserName = value;
					this.SendPropertyChanged("WX_UserName");
					this.OnWX_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid aspnet_UserID
		{
			get
			{
				return this._aspnet_UserID;
			}
			set
			{
				if ((this._aspnet_UserID != value))
				{
					this.Onaspnet_UserIDChanging(value);
					this.SendPropertyChanging();
					this._aspnet_UserID = value;
					this.SendPropertyChanged("aspnet_UserID");
					this.Onaspnet_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime TransTime
		{
			get
			{
				return this._TransTime;
			}
			set
			{
				if ((this._TransTime != value))
				{
					this.OnTransTimeChanging(value);
					this.SendPropertyChanging();
					this._TransTime = value;
					this.SendPropertyChanged("TransTime");
					this.OnTransTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GameName
		{
			get
			{
				return this._GameName;
			}
			set
			{
				if ((this._GameName != value))
				{
					this.OnGameNameChanging(value);
					this.SendPropertyChanging();
					this._GameName = value;
					this.SendPropertyChanged("GameName");
					this.OnGameNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GamePeriod", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GamePeriod
		{
			get
			{
				return this._GamePeriod;
			}
			set
			{
				if ((this._GamePeriod != value))
				{
					this.OnGamePeriodChanging(value);
					this.SendPropertyChanging();
					this._GamePeriod = value;
					this.SendPropertyChanged("GamePeriod");
					this.OnGamePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameResult", DbType="NVarChar(100)")]
		public string GameResult
		{
			get
			{
				return this._GameResult;
			}
			set
			{
				if ((this._GameResult != value))
				{
					this.OnGameResultChanging(value);
					this.SendPropertyChanging();
					this._GameResult = value;
					this.SendPropertyChanged("GameResult");
					this.OnGameResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gr_NumTotal", DbType="Int")]
		public System.Nullable<int> Gr_NumTotal
		{
			get
			{
				return this._Gr_NumTotal;
			}
			set
			{
				if ((this._Gr_NumTotal != value))
				{
					this.OnGr_NumTotalChanging(value);
					this.SendPropertyChanging();
					this._Gr_NumTotal = value;
					this.SendPropertyChanged("Gr_NumTotal");
					this.OnGr_NumTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gr_BigSmall", DbType="NVarChar(5)")]
		public string Gr_BigSmall
		{
			get
			{
				return this._Gr_BigSmall;
			}
			set
			{
				if ((this._Gr_BigSmall != value))
				{
					this.OnGr_BigSmallChanging(value);
					this.SendPropertyChanging();
					this._Gr_BigSmall = value;
					this.SendPropertyChanged("Gr_BigSmall");
					this.OnGr_BigSmallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gr_SingleDouble", DbType="NVarChar(5)")]
		public string Gr_SingleDouble
		{
			get
			{
				return this._Gr_SingleDouble;
			}
			set
			{
				if ((this._Gr_SingleDouble != value))
				{
					this.OnGr_SingleDoubleChanging(value);
					this.SendPropertyChanging();
					this._Gr_SingleDouble = value;
					this.SendPropertyChanged("Gr_SingleDouble");
					this.OnGr_SingleDoubleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gr_DragonTiger", DbType="NVarChar(5)")]
		public string Gr_DragonTiger
		{
			get
			{
				return this._Gr_DragonTiger;
			}
			set
			{
				if ((this._Gr_DragonTiger != value))
				{
					this.OnGr_DragonTigerChanging(value);
					this.SendPropertyChanging();
					this._Gr_DragonTiger = value;
					this.SendPropertyChanged("Gr_DragonTiger");
					this.OnGr_DragonTigerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Type", DbType="NVarChar(5)")]
		public string Buy_Type
		{
			get
			{
				return this._Buy_Type;
			}
			set
			{
				if ((this._Buy_Type != value))
				{
					this.OnBuy_TypeChanging(value);
					this.SendPropertyChanging();
					this._Buy_Type = value;
					this.SendPropertyChanged("Buy_Type");
					this.OnBuy_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Value", DbType="NVarChar(5)")]
		public string Buy_Value
		{
			get
			{
				return this._Buy_Value;
			}
			set
			{
				if ((this._Buy_Value != value))
				{
					this.OnBuy_ValueChanging(value);
					this.SendPropertyChanging();
					this._Buy_Value = value;
					this.SendPropertyChanged("Buy_Value");
					this.OnBuy_ValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Ratio", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Buy_Ratio
		{
			get
			{
				return this._Buy_Ratio;
			}
			set
			{
				if ((this._Buy_Ratio != value))
				{
					this.OnBuy_RatioChanging(value);
					this.SendPropertyChanging();
					this._Buy_Ratio = value;
					this.SendPropertyChanged("Buy_Ratio");
					this.OnBuy_RatioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Buy_Point", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Buy_Point
		{
			get
			{
				return this._Buy_Point;
			}
			set
			{
				if ((this._Buy_Point != value))
				{
					this.OnBuy_PointChanging(value);
					this.SendPropertyChanging();
					this._Buy_Point = value;
					this.SendPropertyChanged("Buy_Point");
					this.OnBuy_PointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result_Point", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Result_Point
		{
			get
			{
				return this._Result_Point;
			}
			set
			{
				if ((this._Result_Point != value))
				{
					this.OnResult_PointChanging(value);
					this.SendPropertyChanging();
					this._Result_Point = value;
					this.SendPropertyChanged("Result_Point");
					this.OnResult_PointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result_HaveProcess", DbType="Bit")]
		public System.Nullable<bool> Result_HaveProcess
		{
			get
			{
				return this._Result_HaveProcess;
			}
			set
			{
				if ((this._Result_HaveProcess != value))
				{
					this.OnResult_HaveProcessChanging(value);
					this.SendPropertyChanging();
					this._Result_HaveProcess = value;
					this.SendPropertyChanged("Result_HaveProcess");
					this.OnResult_HaveProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GameLocalPeriod", DbType="NVarChar(100)")]
		public string GameLocalPeriod
		{
			get
			{
				return this._GameLocalPeriod;
			}
			set
			{
				if ((this._GameLocalPeriod != value))
				{
					this.OnGameLocalPeriodChanging(value);
					this.SendPropertyChanging();
					this._GameLocalPeriod = value;
					this.SendPropertyChanged("GameLocalPeriod");
					this.OnGameLocalPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GP_LastModify", DbType="DateTime")]
		public System.Nullable<System.DateTime> GP_LastModify
		{
			get
			{
				return this._GP_LastModify;
			}
			set
			{
				if ((this._GP_LastModify != value))
				{
					this.OnGP_LastModifyChanging(value);
					this.SendPropertyChanging();
					this._GP_LastModify = value;
					this.SendPropertyChanged("GP_LastModify");
					this.OnGP_LastModifyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WX_UserChangeLog")]
	public partial class WX_UserChangeLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _WX_UserName;
		
		private System.Guid _aspnet_UserID;
		
		private System.DateTime _ChangeTime;
		
		private string _Remark;
		
		private string _RemarkType;
		
		private System.Nullable<decimal> _ChangePoint;
		
		private System.Nullable<bool> _NeedNotice;
		
		private System.Nullable<bool> _HaveNotice;
		
		private System.Nullable<bool> _FinalStatus;
		
		private string _GamePeriod;
		
		private string _BuyValue;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWX_UserNameChanging(string value);
    partial void OnWX_UserNameChanged();
    partial void Onaspnet_UserIDChanging(System.Guid value);
    partial void Onaspnet_UserIDChanged();
    partial void OnChangeTimeChanging(System.DateTime value);
    partial void OnChangeTimeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnRemarkTypeChanging(string value);
    partial void OnRemarkTypeChanged();
    partial void OnChangePointChanging(System.Nullable<decimal> value);
    partial void OnChangePointChanged();
    partial void OnNeedNoticeChanging(System.Nullable<bool> value);
    partial void OnNeedNoticeChanged();
    partial void OnHaveNoticeChanging(System.Nullable<bool> value);
    partial void OnHaveNoticeChanged();
    partial void OnFinalStatusChanging(System.Nullable<bool> value);
    partial void OnFinalStatusChanged();
    partial void OnGamePeriodChanging(string value);
    partial void OnGamePeriodChanged();
    partial void OnBuyValueChanging(string value);
    partial void OnBuyValueChanged();
    #endregion
		
		public WX_UserChangeLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WX_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string WX_UserName
		{
			get
			{
				return this._WX_UserName;
			}
			set
			{
				if ((this._WX_UserName != value))
				{
					this.OnWX_UserNameChanging(value);
					this.SendPropertyChanging();
					this._WX_UserName = value;
					this.SendPropertyChanged("WX_UserName");
					this.OnWX_UserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_UserID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid aspnet_UserID
		{
			get
			{
				return this._aspnet_UserID;
			}
			set
			{
				if ((this._aspnet_UserID != value))
				{
					this.Onaspnet_UserIDChanging(value);
					this.SendPropertyChanging();
					this._aspnet_UserID = value;
					this.SendPropertyChanged("aspnet_UserID");
					this.Onaspnet_UserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangeTime", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ChangeTime
		{
			get
			{
				return this._ChangeTime;
			}
			set
			{
				if ((this._ChangeTime != value))
				{
					this.OnChangeTimeChanging(value);
					this.SendPropertyChanging();
					this._ChangeTime = value;
					this.SendPropertyChanged("ChangeTime");
					this.OnChangeTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(500)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RemarkType", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RemarkType
		{
			get
			{
				return this._RemarkType;
			}
			set
			{
				if ((this._RemarkType != value))
				{
					this.OnRemarkTypeChanging(value);
					this.SendPropertyChanging();
					this._RemarkType = value;
					this.SendPropertyChanged("RemarkType");
					this.OnRemarkTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChangePoint", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> ChangePoint
		{
			get
			{
				return this._ChangePoint;
			}
			set
			{
				if ((this._ChangePoint != value))
				{
					this.OnChangePointChanging(value);
					this.SendPropertyChanging();
					this._ChangePoint = value;
					this.SendPropertyChanged("ChangePoint");
					this.OnChangePointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NeedNotice", DbType="Bit")]
		public System.Nullable<bool> NeedNotice
		{
			get
			{
				return this._NeedNotice;
			}
			set
			{
				if ((this._NeedNotice != value))
				{
					this.OnNeedNoticeChanging(value);
					this.SendPropertyChanging();
					this._NeedNotice = value;
					this.SendPropertyChanged("NeedNotice");
					this.OnNeedNoticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HaveNotice", DbType="Bit")]
		public System.Nullable<bool> HaveNotice
		{
			get
			{
				return this._HaveNotice;
			}
			set
			{
				if ((this._HaveNotice != value))
				{
					this.OnHaveNoticeChanging(value);
					this.SendPropertyChanging();
					this._HaveNotice = value;
					this.SendPropertyChanged("HaveNotice");
					this.OnHaveNoticeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalStatus", DbType="Bit")]
		public System.Nullable<bool> FinalStatus
		{
			get
			{
				return this._FinalStatus;
			}
			set
			{
				if ((this._FinalStatus != value))
				{
					this.OnFinalStatusChanging(value);
					this.SendPropertyChanging();
					this._FinalStatus = value;
					this.SendPropertyChanged("FinalStatus");
					this.OnFinalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GamePeriod", DbType="NVarChar(50)")]
		public string GamePeriod
		{
			get
			{
				return this._GamePeriod;
			}
			set
			{
				if ((this._GamePeriod != value))
				{
					this.OnGamePeriodChanging(value);
					this.SendPropertyChanging();
					this._GamePeriod = value;
					this.SendPropertyChanged("GamePeriod");
					this.OnGamePeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BuyValue", DbType="NVarChar(50)")]
		public string BuyValue
		{
			get
			{
				return this._BuyValue;
			}
			set
			{
				if ((this._BuyValue != value))
				{
					this.OnBuyValueChanging(value);
					this.SendPropertyChanging();
					this._BuyValue = value;
					this.SendPropertyChanged("BuyValue");
					this.OnBuyValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Logic_WX_UserGameLog_DealResult
	{
		
		private System.Nullable<decimal> _Remainder;
		
		private string _WX_UserName;
		
		private System.Guid _aspnet_UserID;
		
		public Logic_WX_UserGameLog_DealResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remainder", DbType="Decimal(18,6)")]
		public System.Nullable<decimal> Remainder
		{
			get
			{
				return this._Remainder;
			}
			set
			{
				if ((this._Remainder != value))
				{
					this._Remainder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WX_UserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string WX_UserName
		{
			get
			{
				return this._WX_UserName;
			}
			set
			{
				if ((this._WX_UserName != value))
				{
					this._WX_UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aspnet_UserID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid aspnet_UserID
		{
			get
			{
				return this._aspnet_UserID;
			}
			set
			{
				if ((this._aspnet_UserID != value))
				{
					this._aspnet_UserID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
